export const root_repo = 'gisk_root_repo'
//export const key = '553f923e432a48b9f70d9eae6566c341'
export const gitee_default_path = 'https://gitee.com/api/v5/repos'



// post
export const url_create_repo = 'https://gitee.com/api/v5/user/repos'

//get
export const url_list_repos = 'https://gitee.com/api/v5/user/repos'
//export const url_list_cont = 'https://gitee.com/api/v5/repos'
//export const url_get_repo_file = 'https://gitee.com/api/v5/repos'
//export const url_get_repo = 'https://gitee.com/api/v5/repos'

//delete
//export const url_delete_repo = 'https://gitee.com/api/v5/repos'
//export const url_delete_repo_file = 'https://gitee.com/api/v5/repos'

